name: "Post issue"
description: "Create or comment on existing issue"

inputs:
  token:
    description: "GITHUB_TOKEN or a repo scoped PAT"
    default: ${{ github.token }}
  title:
    description: "The title of the issue to create"
    required: true
  body:
    description: "The body of the issue or comment"
    required: true
  unique-title-includes:
    description: "The unique title to search for in the repository; if found, a comment will be posted"
    required: true
  labels:
    description: "Labels to use when creating an issue"
    required: false

outputs:
  issue-number:
    description: "The ID of the issue created or commented on"
    value: ${{ steps.result.outputs.issue-number }}

runs:
  using: "composite"
  steps:
    - name: Find issue
      id: find-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "find-issues"
        title-includes: ${{ inputs.unique-title-includes }}

    - name: Get issue number
      shell: bash
      id: get-issue-number
      run: |
        issues=$(cat <<EOF
        ${{ steps.find-issue.outputs.issues }}
        EOF
        )
        if [ "$issues" != "[]" ]; then
          echo "issue-number=$(echo $issues | jq -r '.[0].number')" >> $GITHUB_OUTPUT
        fi

    - name: Create issue
      if: steps.get-issue-number.outputs.issue-number == ''
      id: create-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "create-issue"
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        labels: ${{ inputs.labels }}

    - name: Comment on existing issue
      if: steps.get-issue-number.outputs.issue-number != ''
      id: comment-on-issue
      uses: actions-cool/issues-helper@v3
      with:
        token: ${{ inputs.token }}
        actions: "create-comment"
        issue-number: ${{ steps.get-issue-number.outputs.issue-number }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}

    - name: Result
      shell: bash
      id: result
      run: |
        if [ -n "${{ steps.get-issue-number.outputs.issue-number }}" ]; then
          echo "issue-number=${{ steps.get-issue-number.outputs.issue-number }}" >> $GITHUB_OUTPUT
        elif [ -n "${{ steps.create-issue.outputs.issue-number }}" ]; then
          echo "issue-number=${{ steps.create-issue.outputs.issue-number }}" >> $GITHUB_OUTPUT
        fi