load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

# gazelle:prefix github.com/cockroachdb/pebble
# gazelle:build_file_name BUILD

go_library(
    name = "go_default_library",
    srcs = [
        "batch.go",
        "cache.go",
        "checkpoint.go",
        "cleaner.go",
        "commit.go",
        "compaction.go",
        "compaction_iter.go",
        "compaction_picker.go",
        "comparer.go",
        "db.go",
        "error_iter.go",
        "event.go",
        "filenames.go",
        "get_iter.go",
        "ingest.go",
        "internal.go",
        "iterator.go",
        "level_iter.go",
        "log_recycler.go",
        "logger.go",
        "mem_table.go",
        "merger.go",
        "merging_iter.go",
        "merging_iter_heap.go",
        "metrics.go",
        "open.go",
        "options.go",
        "pacer.go",
        "race_off.go",
        "race_on.go",
        "read_state.go",
        "snapshot.go",
        "syncing_fs.go",
        "table_cache.go",
        "version_set.go",
    ],
    importpath = "github.com/cockroachdb/pebble",
    visibility = ["//visibility:public"],
    deps = [
        "//internal/arenaskl:go_default_library",
        "//internal/base:go_default_library",
        "//internal/batchskl:go_default_library",
        "//internal/bytealloc:go_default_library",
        "//internal/cache:go_default_library",
        "//internal/humanize:go_default_library",
        "//internal/manifest:go_default_library",
        "//internal/private:go_default_library",
        "//internal/rangedel:go_default_library",
        "//internal/rate:go_default_library",
        "//internal/rawalloc:go_default_library",
        "//internal/record:go_default_library",
        "//sstable:go_default_library",
        "//vfs:go_default_library",
    ],
)

filegroup(
    name = "testdata",
    data = glob(["testdata/**"]),
    visibility = ["//:__subpackages__"],
)

go_test(
    name = "go_default_test",
    size = "small",
    srcs = [
        "batch_test.go",
        "checkpoint_test.go",
        "cleaner_test.go",
        "commit_test.go",
        "compaction_iter_test.go",
        "compaction_picker_test.go",
        "compaction_test.go",
        "data_test.go",
        "db_test.go",
        "error_test.go",
        "event_listener_test.go",
        "flush_test.go",
        "get_iter_test.go",
        "ingest_test.go",
        "internal_test.go",
        "iterator_test.go",
        "level_iter_test.go",
        "log_recycler_test.go",
        "mem_table_test.go",
        "merging_iter_test.go",
        "metrics_test.go",
        "open_test.go",
        "options_test.go",
        "pacer_test.go",
        "range_del_test.go",
        "read_state_test.go",
        "snapshot_test.go",
        "table_cache_test.go",
    ],
    data = [":testdata"],
    embed = [":go_default_library"],
    deps = [
        "//internal/arenaskl:go_default_library",
        "//internal/base:go_default_library",
        "//internal/cache:go_default_library",
        "//internal/datadriven:go_default_library",
        "//internal/manifest:go_default_library",
        "//internal/rangedel:go_default_library",
        "//internal/record:go_default_library",
        "//sstable:go_default_library",
        "//vendor/github.com/kr/pretty:go_default_library",
        "//vendor/github.com/stretchr/testify/require:go_default_library",
        "//vendor/golang.org/x/exp/rand:go_default_library",
        "//vfs:go_default_library",
    ],
)
