load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["humanize.go"],
    importpath = "github.com/cockroachdb/pebble/internal/humanize",
    visibility = ["//:__subpackages__"],
)
