# Copyright 2011 The LevelDB-Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=code.google.com/p/leveldb-go/leveldb/memdb
GOFILES=\
	memdb.go\

include $(GOROOT)/src/Make.pkg

