name: Nightly instrumented tests

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.24'
        type: string
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.24'
        type: string

jobs:
  linux-race:
    name: linux-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - run: GOTRACEBACK=all make testrace TAGS=

      - name: Post issue on failure
        if: failure() && inputs.file_issue
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly ${{ github.job }} failed"
          body: "The nightly ${{ github.job }} test run failed on ${{ inputs.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"

  linux-asan:
    name: linux-asan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - run: make testasan

      - name: Post issue on failure
        if: failure() && inputs.file_issue
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly ${{ github.job }} failed"
          body: "The nightly ${{ github.job }} test run failed on ${{ inputs.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"

  linux-msan:
    name: linux-msan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go_version }}

      - run: make testmsan

      - name: Post issue on failure
        if: failure() && inputs.file_issue
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly ${{ github.job }} failed"
          body: "The nightly ${{ github.job }} test run failed on ${{ inputs.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"

