name: Triage new issue

on:
  issues:
    types:
      - opened

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply storage labels
        uses: andymckay/labeler@1.0.2
        with:
          add-labels: 'T-storage,A-storage'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
