name: Nightly stress test

on:
  schedule:
    - cron: '00 10 * * * ' # 10am UTC daily
  workflow_dispatch:

jobs:

  linux-stress:
    name: linux-stress
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Run unit tests under stress
        run: |
          go install github.com/cockroachdb/stress@latest
          scripts/stress.sh

      - name: Post issue on failure
        if: failure()
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "nightly stress tests failed"
          body: "The nightly tress test run failed on ${{ github.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          unique-title-includes: "nightly stress tests failed"
          labels: "C-test-failure"
