name: Nightly instrumented tests

on:
  schedule:
    - cron: "0 7 * * *" # 7am UTC, daily.
  workflow_dispatch:

jobs:
  linux-race:
    name: linux-race
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - run: GOTRACEBACK=all make testrace TAGS=

      - name: Post issue on failure
        if: failure()
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "nightly testrace failed"
          body: "The nightly testrace run failed on ${{ github.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          unique-title-includes: "nightly testrace failed"
          labels: "C-test-failure"

  linux-asan:
    name: linux-asan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - run: make testasan

      - name: Post issue on failure
        if: failure()
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "nightly testasan failed"
          body: "The nightly asan test run failed on ${{ github.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          unique-title-includes: "nightly testasan failed"
          labels: "C-test-failure"

  linux-msan:
    name: linux-msan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - run: make testmsan

      - name: Post issue on failure
        if: failure()
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "nightly testmsan failed"
          body: "The nightly msan test run failed on ${{ github.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          unique-title-includes: "nightly testmsan failed"
          labels: "C-test-failure"

