name: Test s390x

on:
  workflow_call:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.23'
        type: string
  workflow_dispatch:
    inputs:
      sha:
        description: 'SHA to run against'
        required: false
        type: string
      file_issue_branch:
        description: 'Branch used in filed issues; if unset, no issues are filed'
        required: false
        type: string
      go_version:
        description: 'Go version'
        required: false
        default: '1.23'
        type: string

permissions:
  issues: write

jobs:
  linux-qemu-s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha || github.sha }}

      - name: Install qemu
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          qemu-s390x-static --version

      - name: Run tests in container
        run: make test-s390x-qemu S390X_GOVERSION=${{ inputs.go_version }}

      - name: Post issue on failure
        if: failure() && inputs.file_issue_branch != ''
        id: create-or-update-unique-issue
        uses: ./.github/actions/post-issue
        with:
          title: "${{ inputs.file_issue_branch }}: nightly s390x test failed"
          body: "The nightly ${{ github.job_id }} test run failed on ${{ inputs.sha }}. Please review the run [here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})."
          labels: "C-test-failure"
